language: cpp
dist: focal
sudo: require
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake

before_install:
  - wget -O cmake/CPM.cmake https://github.com/cpm-cmake/CPM.cmake/releases/latest/download/get_cpm.cmake

script: 
  - cmake -S . -B build -DBUILD_WITH_TEST=ON -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_CXX_FLAGS="-Wall"
  - cmake --build build
  - ./build/test/minimalcpppj
