dist: focal
os: linux
language: cpp
cache: ccache
env:
  global:
    secure: O6SyMeVHcyvyZIvh0cJNYkwdBp52o9R9dFRJxNrho0uuYVG6EipEWsTlBuqOoIx9gmdjZ0V6z1rJGDOiQKACWTgMnq7+FKuQVK1Se9sBKNNCYnyPXOgZYILAJBFS2PA6xZqGgNttZrWAKmRZWTU8pX10EaFZeX6tDCmUrWI9yCOYGXZ7RBcuITvUPhYq5eTLpc0nZ+fqZ8vrcRV14S1WxQD/Gn7Mj7d21QPmWhIwkMsbugWYphR6BE0r2cA4WEIVLYGO0su4yxNuiDvB1mwelZB+NUnR0c3DLR6Nq7oCKC4bJjR3qARw3Y5yR8fUZ8sJZ88k2I2yCAPolTfnx8rznQmv4j6eYzOrFJP6kHjjg0gAUm6Oh1Rnrmz3tjRR6GhwKUlDuW698fxI2u2D6Wsx3bKbMIPP1hN1f1Ef7n+80clQdXCsZGWWuBxYpD2/KuCsVYQTLhmNWUfeHxeTX6o2to/LibOfbGQnwUODSdq0Bz8Z8FWfIjrt85r+cQOGFd+/VfE2pB7SBd9eIbsEPtN8F3Iw7izIkh9KWj4db/8bLgXVjDBNmDG512WAvO3mxG06PtTQoMc3jnBimfUbtRWwvz+J/EwvqWyS6rLHbjzzJhiFb/qmnPi5tMb+ebAwvgpQztCiqdlMn8HOujH5UyvxdYkb2peGMJAtVGzejZRhZ0Q=
jobs:
  include:
    - compiler: gcc
      env:
        - COVERAGE=true
        - TEST_ON=ON
        - CXX_FLAGS="-O0 -g --coverage"
      addons:
        apt:
          packages: lcov
        coverity_scan:
          project:
            name: "$TRAVIS_REPO_SLUG"
          build_command_prepend: cmake -S . -B build -DBUILD_WITH_TEST=ON
          build_command: cmake --build build
          branch_pattern: coverity_scan
          notification_email: jimbi.o.nanamemaegami@gmail.com
    - compiler: gcc
      env:
        - TEST_ON=OFF
    - compiler: gcc
      env:
        - LIB_MODE=ON
    - compiler: clang
      env:
        - TEST_ON=ON
    - compiler: clang
      env:
        - TEST_ON=OFF
    - compiler: clang
      env:
        - LIB_MODE=ON
before_install: |
  mkdir -p $HOME/.ccache
  mkdir -p $HOME/.ccache/CPM
script: |
  cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_WITH_TEST=${TEST_ON} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCPM_SOURCE_CACHE=$HOME/.ccache/CPM -DCMAKE_CXX_FLAGS="$CXX_FLAGS"
  cmake --build build
  ./build/minimalcpppj
after_success: |
  if [ $COVERAGE == true ] ; then bash -x scripts/run-codecov.sh; fi
