version: 1.0.{build}

image:
- Visual Studio 2019
- Visual Studio 2017

configuration:
- Debug
- Release

before_build:
- cmd:
    cmake -S . -B build -DBUILD_WITH_TEST=ON

build:
  project: build\minimalcpppj.sln
  verbosity: normal
