version: 1.0.{build}

image:
- Visual Studio 2019
- Visual Studio 2017

configuration:
- Debug
- Release

environment:
  matrix:
  - BUILD_OPTIONS: -DBUILD_WITH_TEST=ON
  - BUILD_OPTIONS: -DBUILD_WITH_TEST=OFF
  - BUILD_OPTIONS: -DLIB_MODE=ON

before_build:
- cmd:
    cmake -S . -B build $BUILD_OPTIONS

build:
  project: build\minimalcpppj.sln
  verbosity: normal
